# fly.toml app configuration file generated for lucasamberg-dev on 2023-12-20T19:41:42-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lucasamberg-dev"
primary_region = "lax"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
